In [1]:
import torch
import torch.nn as nn

In [6]:
emb = nn.Embedding(10, 3)

In [18]:
a = torch.randn((3, 4, 4))
a

tensor([[[-0.3999,  0.4728, -0.0120,  1.0840],
         [ 2.0123, -0.3719, -0.7180,  1.4322],
         [-0.4980,  0.1382, -1.4327, -1.2919],
         [ 1.6408, -1.3323, -0.4059,  0.7037]],

        [[ 1.0799,  0.1148, -1.7915,  0.4265],
         [-0.4793, -1.1954, -0.2067,  0.7051],
         [-0.5301, -0.6336, -1.6611,  0.3500],
         [-0.4226, -1.0847, -0.4694,  1.4741]],

        [[-1.2822, -1.2061, -0.3136, -0.8308],
         [-0.7126,  0.7396, -0.4404,  0.5400],
         [ 0.7501,  0.0280,  0.0547, -1.1873],
         [-0.2429,  1.9523, -0.8515, -0.4893]]])

In [26]:
x1, x2 = torch.split(a, [1, 3], dim=-1)
print(x1, x2)

tensor([[[-0.3999],
         [ 2.0123],
         [-0.4980],
         [ 1.6408]],

        [[ 1.0799],
         [-0.4793],
         [-0.5301],
         [-0.4226]],

        [[-1.2822],
         [-0.7126],
         [ 0.7501],
         [-0.2429]]]) tensor([[[ 0.4728, -0.0120,  1.0840],
         [-0.3719, -0.7180,  1.4322],
         [ 0.1382, -1.4327, -1.2919],
         [-1.3323, -0.4059,  0.7037]],

        [[ 0.1148, -1.7915,  0.4265],
         [-1.1954, -0.2067,  0.7051],
         [-0.6336, -1.6611,  0.3500],
         [-1.0847, -0.4694,  1.4741]],

        [[-1.2061, -0.3136, -0.8308],
         [ 0.7396, -0.4404,  0.5400],
         [ 0.0280,  0.0547, -1.1873],
         [ 1.9523, -0.8515, -0.4893]]])


In [76]:
a = torch.tensor(1)
print(type(a))
x = torch.randn((3, 3))

<class 'torch.Tensor'>


In [77]:
mask = torch.tensor([1, 1, 0]).bool()

y = torch.tril(
            torch.ones(3, 3).bool()
        )

x = x.masked_fill(y[:, :] == 0, float('-inf'))
print(x)
x = torch.nn.functional.softmax(x, dim=-1)
print(x)

tensor([[-0.6475,    -inf,    -inf],
        [ 0.1430,  0.4731,    -inf],
        [ 2.1550,  0.8124, -1.9517]])
tensor([[1.0000, 0.0000, 0.0000],
        [0.4182, 0.5818, 0.0000],
        [0.7827, 0.2044, 0.0129]])
