In [2]:
import torch
import torch.nn as nn

In [3]:
emb = nn.Embedding(10, 3)

In [4]:
a = torch.randn((3, 4, 4))
a

tensor([[[-1.8206,  1.5690, -1.5600,  0.6775],
         [ 1.0036, -0.0584,  0.3968, -0.0688],
         [ 0.3319, -0.5165,  0.5171,  0.8773],
         [-0.8071, -2.6161,  0.8509,  0.9387]],

        [[ 1.1609,  0.8646, -0.5164,  0.2494],
         [-1.3218,  0.4365,  0.0377,  0.6101],
         [-0.2902,  0.5339,  1.0100, -1.2560],
         [ 0.7500,  1.4133,  0.9081,  1.7034]],

        [[ 0.4955,  1.2332, -0.8913, -2.8097],
         [ 0.6129, -1.7710, -0.2884, -0.3802],
         [ 1.9636,  0.2992, -0.0196,  0.0211],
         [-0.3136,  1.1228,  1.0822,  0.0360]]])

In [5]:
x1, x2 = torch.split(a, [1, 3], dim=-1)
print(x1, x2)

tensor([[[-1.8206],
         [ 1.0036],
         [ 0.3319],
         [-0.8071]],

        [[ 1.1609],
         [-1.3218],
         [-0.2902],
         [ 0.7500]],

        [[ 0.4955],
         [ 0.6129],
         [ 1.9636],
         [-0.3136]]]) tensor([[[ 1.5690, -1.5600,  0.6775],
         [-0.0584,  0.3968, -0.0688],
         [-0.5165,  0.5171,  0.8773],
         [-2.6161,  0.8509,  0.9387]],

        [[ 0.8646, -0.5164,  0.2494],
         [ 0.4365,  0.0377,  0.6101],
         [ 0.5339,  1.0100, -1.2560],
         [ 1.4133,  0.9081,  1.7034]],

        [[ 1.2332, -0.8913, -2.8097],
         [-1.7710, -0.2884, -0.3802],
         [ 0.2992, -0.0196,  0.0211],
         [ 1.1228,  1.0822,  0.0360]]])


In [6]:
a = torch.tensor(1)
print(type(a))
x = torch.randn((3, 3))

<class 'torch.Tensor'>


In [7]:
mask = torch.tensor([1, 1, 0]).bool()

y = torch.tril(
            torch.ones(3, 3).bool()
        )

x = x.masked_fill(y[:, :] == 0, float('-inf'))
print(x)
x = torch.nn.functional.softmax(x, dim=-1)
print(x)

tensor([[-1.1818,    -inf,    -inf],
        [ 0.0270,  1.1917,    -inf],
        [ 1.2651, -0.5784, -0.4036]])
tensor([[1.0000, 0.0000, 0.0000],
        [0.2378, 0.7622, 0.0000],
        [0.7425, 0.1175, 0.1400]])


In [10]:
n = nn.ModuleDict({
    'a': nn.Linear(3, 3),
    'b': nn.Linear(3, 3)
})
print(n.keys())

dict_keys(['a', 'b'])
